import os
from langchain_community.tools import (
    QuerySQLDatabaseTool,
    InfoSQLDatabaseTool,
    ListSQLDatabaseTool,
)
from langchain_community.utilities import SQLDatabase
import urllib.parse
from langchain_core.tools import tool
import re
import json

from multi_agents.utils.logger import setup_logger

logger = setup_logger()

user = os.getenv("POSTGRES_USER")
password = urllib.parse.quote_plus(os.getenv("POSTGRES_PASSWORD"))
db_name = os.getenv("POSTGRES_DB")
port = os.getenv("POSTGRES_PORT")
host = os.getenv("POSTGRES_HOST", "localhost")
db = SQLDatabase.from_uri(f"postgresql://{user}:{password}@{host}:{port}/{db_name}")

execute_query_tool = QuerySQLDatabaseTool(db=db)
get_schema_tool = InfoSQLDatabaseTool(db=db)
list_tables_tool = ListSQLDatabaseTool(db=db)


@tool
def safe_execute_query(query: str) -> str:
    """
    Executes a SQL SELECT query against the database with built-in safety guardrails.
    :param query: The raw SQL string generated by the LLM to be executed.
                  Example: "SELECT customer_id, email FROM users WHERE active = true"
    :return: If successful, returns the query results as a string (typically a formatted
             list of tuples).
             If a security violation occurs, returns a string detailing the violation.
             If a SQL syntax error or connection error occurs, catches the exception and
             returns the error message as a string to allow the agent to self-correct.
    """
    forbidden_words = r"\b(DELETE|DROP|ALTER|TRUNCATE|GRANT|REVOKE|COMMIT|ROLLBACK)\b"
    if re.search(forbidden_words, query, re.IGNORECASE):
        return (
            "Error: Security violation. You are only permitted to run SELECT queries."
        )
    try:
        query_results = execute_query_tool.invoke(query)
        return json.dumps({"query_results": query_results})
    except Exception as e:
        return f"Error executing query: {str(e)}"


sql_tools = [safe_execute_query, get_schema_tool, list_tables_tool]
